USE mysql_db;

INSERT INTO `members` (`email`,
                       `password`,
                       `name`,
                       `nickname`,
                       `country`,
                       `english_level`,
                       `interest`,
                       `description`,
                       `role`,
                       `membership_grade`,
                       `last_sign_in_at`,
                       `is_blocked`,
                       `is_deleted`)
VALUES ('coder.dev@mixchat.com',
        '$2a$10$k1PEYBKO83YurbOiVR/tc.HUEdc9w9ZTYPlYTjBznNcNiWnZ6Bl5S', -- test1234
        '김현수',
        'SpringMaster',
        'KR',
        'INTERMEDIATE',
        'Backend, Spring, Database',
        'Spring 부트 개발자입니다. 기술 토론을 좋아해요.',
        'USER',
        'BASIC',
        NOW(),
        FALSE,
        FALSE),
       ('traveler.john@mixchat.com',
        '$2a$10$k1PEYBKO83YurbOiVR/tc.HUEdc9w9ZTYPlYTjBznNcNiWnZ6Bl5S',
        'John Smith',
        'WorldExplorer',
        'US',
        'NATIVE',
        'Travel, Photography, History',
        '새로운 문화를 배우는 것을 즐깁니다.',
        'USER',
        'PREMIUM',
        NOW(),
        FALSE,
        FALSE),
       ('admin.user@mixchat.com',
        '$2a$10$k1PEYBKO83YurbOiVR/tc.HUEdc9w9ZTYPlYTjBznNcNiWnZ6Bl5S',
        '박관리',
        'SiteManager',
        'KR',
        'ADVANCED',
        'Management, Policy',
        '사이트 운영 및 관리를 담당합니다.',
        'ADMIN', -- 관리자 역할
        'BASIC',
        NOW(),
        FALSE,
        FALSE);

-- 차단 멤버
INSERT INTO `members` (`email`,
                       `password`,
                       `name`,
                       `nickname`,
                       `country`,
                       `english_level`,
                       `interest`,
                       `description`,
                       `role`,
                       `membership_grade`,
                       `last_sign_in_at`,
                       `is_blocked`,
                       `blocked_at`,
                       `is_deleted`)
VALUES ('blocked.user@mixchat.com',
        '$2a$10$k1PEYBKO83YurbOiVR/tc.HUEdc9w9ZTYPlYTjBznNcNiWnZ6Bl5S',
        '최차단',
        'BadBehavior',
        'CN',
        'BEGINNER',
        'Games',
        '차단된 사용자입니다.',
        'USER',
        'BASIC',
        NOW(),
        TRUE,
        NOW(), -- 👈 blocked_at 필드에 현재 시각 삽입
        FALSE);

-- 삭제 멤버
INSERT INTO `members` (`email`,
                       `password`,
                       `name`,
                       `nickname`,
                       `country`,
                       `english_level`,
                       `interest`,
                       `description`,
                       `role`,
                       `membership_grade`,
                       `last_sign_in_at`,
                       `is_blocked`,
                       `is_deleted`,
                       `deleted_at`)
VALUES ('deleted.user@mixchat.com',
        '$2a$10$k1PEYBKO83YurbOiVR/tc.HUEdc9w9ZTYPlYTjBznNcNiWnZ6Bl5S',
        '이삭제',
        'GhostUser',
        'JP',
        'INTERMEDIATE',
        'Anime, Movies',
        NULL,
        'USER',
        'BASIC',
        '2025-11-01 10:00:00.000000',
        FALSE,
        TRUE,
        '2025-11-01 10:00:00.000000' -- 👈 deleted_at 필드에 명시된 시각 삽입
       );

INSERT INTO translation_tags (code) VALUES
('GRAMMAR'),
('SPELLING'),
('STRUCTURE'),
('WORD_UNKNOWN');

INSERT INTO prompts (member_id, prompt_type, title, content, scenario_id, created_at, modified_at)
VALUES (1, 'PRE_SCRIPTED', '테스트 프롬프트', '테스트 프롬프트입니다.', 'SCENARIO_001', NOW(), NOW());
